version: "3"
services:
  postgres:
    container_name: setwg-nestjs-postgres
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge
